### ISSUE TITLE
Check for missing commits vs devel

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/kubernetes#49]
##### SUMMARY
The "Big Migration" has now taken place.

As this collection already exists, we need to carefully check to see if any further commits went into devel since this repo was created.

Please check the contents of https://github.com/ansible-collection-migration/community.kubernetes against this repo

##### ISSUE TYPE
- Bug Report

**Comment by geerlingguy** [comment]
@gundalow - Just noting that this repo has also had some commits since it was forked out of `devel`, but I believe https://github.com/ansible-collections/kubernetes/commit/4b6fdb1615f20d58e44c3e562f43cbd72dd30e0c is where we could do a one-by-one diff of the relevant files. I'll work on that today. I tried to make sure none of the PRs against ansible/ansible tagged with `k8s` were unaccounted for here but I could've missed something!

**Comment by gundalow** [comment]
Clarification:
* Please do a per-file level diff against every file in the ansible-collection-migration repo and this one
* Pay care to files added and removed.
* During the last two weeks there have been lots of fixes, especially around and tests, dependencies, and new collection features e.g. meta/action_groups.yml

**Comment by geerlingguy** [comment]
```
git remote add -f migrated_repo https://github.com/ansible-collection-migration/community.kubernetes.git
git remote update
git diff master remotes/migrated_repo/master
git remote rm migrated_repo
```

Here's the output from a one-for-one diff of the two repos (from this repo):

[full-diff.txt](https://github.com/ansible-collections/kubernetes/files/4308491/full-diff.txt)

**Comment by geerlingguy** [comment]
File-by-file breakdown:

- (new) `meta/action_groups.yml` - New file, not sure what this is for?
- (new) `meta/routing.yml` - New file, not sure what this is for?
- (missing) `plugins/connection/kubectl.py` - This is not in the auto-migrated collection
- `plugins/doc_fragments/k8s_auth_options.py` - new param `persist_config`... will need to investigate
- `plugins/doc_fragments/k8s_scale_options.py` - a `required: True` was missing, we fixed that I believe to match argspec
- `plugins/inventory/k8s.py` - `NAME` is different (FQCN)
- `plugins/inventory/openshift.py`
  - Import line looks wrong in this repo's copy
  - `NAME` is different (FQCN)
- `plugins/lookup/k8s.py`
  - Some quoting differences.
  - Removal of 'version_added' line.
- `plugins/lookup/openshift.py` - this file doesn't exist in this collection...
- `plugins/module_utils/common.py` - missing new var `persist_config` in argspec and in `load_kube_config` calls
- `plugins/module_utils/raw.py`
  - additional `import urllib3`
  - `self.get_api_client()` call was wrapped in try/except block
- `plugins/modules/k8s.py`
  - remove all the 'version_added' strings?
  - `c(type)` changed to `C(type)`
  - An instance of `default: True` was changed to `default: no` in suboptions docs...
  - Example 'Create a Service object by reading the definition from a file' was removed
  - Many examples were changed to add a `| from_yaml` filter
- `plugins/modules/k8s_auth.py`  - version_added was removed
- `plugins/modules/k8s_exec.py` - was added to this project, not upstream
- `plugins/modules/k8s_facts.py` - not in this project (was deprecated alias to `k8s_info`)
- `plugins/modules/k8s_info.py` - version_added was removed
- `plugins/modules/k8s_log.py` - was added to this project, not upstream
- `plugins/modules/k8s_raw.py` - not in this project (was deprecated alias to `k8s`)
- `plugins/modules/k8s_scale.py` - version_added was removed
- `plugins/modules/k8s_service.py` - version_added was removed
- `plugins/modules/openshift_raw.py` - not in this project (was deprecated alias to `k8s`)
- `plugins/modules/openshift_scale.py` - not in this project (was deprecated alias to `k8s_scale`)

All the other changes are inconsequential (e.g. test changes, fixes we've done in this repo to whittle down the sanity check `ignore` lists) and/or related to naming (e.g. modules being in `plugins/k8s` instead of `plugins`).

**Comment by geerlingguy** [comment]
For the missing file, that was a mistake on my part, I forgot to route `kubectl.py` to this collection so it was dumped into `community.general`. I've opened two follow-up issues to fix it:

  - https://github.com/ansible-collection-migration/community.general/issues/1
  - https://github.com/ansible/ansible/issues/68121

**Comment by geerlingguy** [comment]
Two fixes didn't make their way into this collection's code:

  - https://github.com/ansible/ansible/pull/60726 — not sure how since this was merged in September and this repo forked from devel a month ago :/
  - https://github.com/ansible/ansible/pull/63219 — also not sure since this was in December
  - https://github.com/ansible/ansible/pull/65424 — that was merged into devel after this repo forked from devel

**Comment by geerlingguy** [comment]
I'm going to try to get the rests of these fixes in today.

**Comment by geerlingguy** [comment]
I created the above three PRs with commits attributed to the original authors, once tests pass I'll merge them in order. It seems like they will not conflict in any way so it should just be a matter of waiting for all of them to pass.

Note that #55 and #56 at least (not sure about #54) were slated for 2.10, so if we add the change to the 0.9.x release series it would be a feature addition that would likely wind up in Ansible 2.10/ACD. I'm okay with that as it doesn't seem to be a _breaking_ change... but just wanted to point that out.

The first ACD release could be a bit of a wild ride, at least for any modules that are actively maintained between now and it's release day...

**Comment by geerlingguy** [comment]
Those three PRs are in, but I'm going to have to pause the fixing of the rest of the minor changes (mostly taking out `version_added` since that's not relevant in this collection anymore...).

**Comment by geerlingguy** [comment]
I'm not going to add `action_groups.yml` for now; see https://github.com/ansible-collections/kubernetes/issues/58 for follow-up.

**Comment by geerlingguy** [comment]
Not going to touch the `routing.yml` file for now either. Not sure if any of that is required since this collection is not going to support deprecated modules.

**Comment by geerlingguy** [comment]
PR with final fixes for this issue: https://github.com/ansible-collections/kubernetes/pull/59
