### ISSUE TITLE
[WARNING]: - collection was NOT installed successfully: Content has no field named 'owner'

### ISSUE THREAD

**Issue by onknows** [ansible-collections/kubernetes#62]
##### SUMMARY

This collection willl not install as described in README.md because an owner field is missing. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Ansible Galaxy

##### ANSIBLE VERSION
```paste below
user:~] 1 $ ansible --version
ansible 2.8.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ostraaten/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]
[user:~] $ 

```

##### CONFIGURATION

```paste below
[user:~] $ ansible-config dump --only-changed
[yser $ 


```

##### OS / ENVIRONMENT

Ubuntu 18.04 LTS

##### STEPS TO REPRODUCE
You only need Ansible installed to reproduce this bug

```yaml

```

##### EXPECTED RESULTS

i expect Ansible to download and install the collection. 

##### ACTUAL RESULTS

```paste below
[user:~] 5 $ ansible-galaxy collection install community.kubernetes
- downloading role 'collection', owned by 
 [WARNING]: - collection was NOT installed successfully: Content has no field
named 'owner'

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

When ignoring errors it still will not install
```[user:~] $ ansible-galaxy collection install community.kubernetes --ignore-errors
- downloading role 'collection', owned by 
 [WARNING]: - collection was NOT installed successfully: Content has no field named 'owner'

- downloading role 'kubernetes', owned by community
 [WARNING]: - community.kubernetes was NOT installed successfully: - sorry, community.kubernetes was not found on
https://galaxy.ansible.com.
```

**Comment by geerlingguy** [comment]
@onknows - In the output, it looks like it's trying to install roles:

```
- downloading role 'collection', owned by 
...
- downloading role 'kubernetes', owned by community
```

I can't reproduce this error with Ansible 2.9.5 (haven't installed 2.8.3 to test with that version though). Note that `owner` is not a required field for collections, so I'm not sure where that message comes from—however doing some searches I found issues like https://github.com/ansible/galaxy/issues/2037#issuecomment-537237801, which indicate that the way you install collections with `ansible-galaxy` may have changed between 2.8 and 2.9?

I would suggest filing an issue in ansible/ansible if there is a bug with the way collections are installed in 2.8 and it's impossible to install them; that's not something we can solve in a downstream collection, since it has to do with the `ansible-galaxy` cli which is maintained in the ansible/ansible repository.
